import type { Metadata } from 'next';
import AppContent from './AppContent';
import { AppSidebar } from './components/Sections/AppSidebar';
import { SidebarProvider, SidebarTrigger } from './components/ui/sidebar';
import './globals.css';

export const metadata: Metadata = {
  title: 'Informium',
  description: 'Generated by create next app',
  icons: {
    icon: '/informiumLogo.png',
    shortcut: '/informiumLogo.png',
    apple: '/informiumLogo.png',
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="font-sans">
        <main className="flex flex-col min-h-screen">
          <AppContent>{children}</AppContent>
        </main>
      </body>
    </html>
  );
}
