import type { Metadata } from 'next';
import { AppSidebar } from './components/Sections/AppSidebar';
import { SidebarProvider, SidebarTrigger } from './components/ui/sidebar';
import './globals.css';

export const metadata: Metadata = {
  title: 'Informium',
  description: 'Generated by create next app',
  icons: {
    icon: '/informiumLogo.png',
    shortcut: '/informiumLogo.png',
    apple: '/informiumLogo.png',
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="font-sans">
        <SidebarProvider>
          <AppSidebar />
          <main>
            <SidebarTrigger />
            {children}
          </main>
        </SidebarProvider>
      </body>
    </html>
  );
}
